name: my_event_plannerokta
description: A Flutter project for managing and planning events
publish_to: 'none'


environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.4
  shared_preferences: ^2.3.3
  image_picker: ^1.0.7
  uuid: ^4.4.0   # <— tambahkan ini

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true


  # Folder aset
  assets:
    - assets/
    - assets/images/
    - assets/videos/


  # Font custom (opsional)
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900